name: Build and Test

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

defaults:
  run:
    shell: bash -el {0}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Anaconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.12"
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: true

      - name: Install ROOT
        run: |
          mamba install root

      - name: Install Geant4
        run: |
          mamba install geant4

      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Help menu
        run: |
          cd build
          ./radiation-decay-secondaries --help
