name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Anaconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.8"
          miniforge-variant: Mambaforge
          use-mamba: true

      - name: Install dependencies
        run: |
          mamba install root

      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          make
